class Commands:
    LEECH = "leech@slpcbot"
    PURGE = "purge@slpcbot"
    PAUSEALL = "pauseall@slpcbot"
    RESUMEALL = "resumeall@slpcbot"
    STATUS = "status@slpcbot"
    SETTINGS = "settings@slpcbot"
    EXEC = "exec@slpcbot"
    UPLOAD = "upload@slpcbot"
    YTDL = "ytdl@slpcbot"
    PYTDL = "pytdl@slpcbot"
    ABOUT = "about@slpcbot"
    GETLOGS = "getlogs@slpcbot"
    SERVER = "server@slpcbot"
    USERSETTINGS = "usetting@slpcbot"
    INSTADL = "instadl@slpcbot"
